version: '3'

services:
  proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - ./conf/fastcgi_params:/etc/nginx/fastcgi_params
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: d0018e.falk-net.se

  #site:
  #  image: nginx:alpine
  #  depends_on:
  #    - db
  #    - php-docker
  #  restart: always
  #  volumes:
  #    - ./src:/srv:ro
  #    - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
  #  environment:
  #    VIRTUAL_HOST: d0018e.falk-net.se
  #    LETSENCRYPT_HOST: d0018e.falk-net.se

  php:
    build: ./conf/php-docker
    depends_on:
      - db
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./config.ini:/usr/share/nginx/html/config.ini:ro
    environment:
      VIRTUAL_HOST: d0018e.falk-net.se
      LETSENCRYPT_HOST: d0018e.falk-net.se
      VIRTUAL_ROOT: /usr/share/nginx/html/public
      VIRTUAL_PROTO: fastcgi
      VIRTUAL_PORT: 9000

  #acme:
  #  image: nginxproxy/acme-companion
  #  depends_on:
  #    - proxy
  #  restart: unless-stopped
  #  volumes_from:
  #    - proxy
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - acme:/etc/acme.sh
  #  environment:
  #    DEFAULT_EMAIL: frefal-9@student.ltu.se

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testing
    volumes:
      - db:/var/lib/mysql

volumes:
  acme:
  certs:
  vhost:
  html:
  db:
