<?php require_once "header.phtml";

?>
<section class="section">
<div class="card">
  <header class="card-header">
    <h1 class="card-header-title">Add book</h1>

  </header>
  <div class="card-content">
    <form action="#" method="post">

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Title</label>
        </div>
        <div class="field-body">
          <div class="field">
            <p class="control">
              <input class="input" name="Title" placeholder="Johan" required>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Price</label>
        </div>
        <div class="field-body">
          <div class="field">
            <p class="control">
              <input class="input" name="Price" type="number" min="0" value="99" required>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Quantity</label>
        </div>
        <div class="field-body">
          <div class="field">
            <p class="control">
              <input class="input" name="Quantity" type="number" min="0" value="0" required>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">description</label>
        </div>
        <div class="field-body">
          <div class="field">
            <p class="control">
              <textarea class="textarea" name="Description"
                        placeholder="Books description"></textarea>
              <!--<input class="input"  type="text" placeholder="Books description" required>-->
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">author</label>
        </div>
        <div class="field-body">
          <div class="field">
            <p class="control">
              <input class="input" name="Author" type="text" placeholder="Ex. Malkolm"required>
            </p>
          </div>
        </div>
      </div>

  </div>
  <footer class="card-footer">
    <input type="submit" value="Submit" class="card-footer-item is-clickable">
  </footer>

  </form>
</div>

<?php require_once "footer.phtml"?>
