<?php require_once "header.phtml"?>

<h2>Create an account</h2>

<p>Please submit Username and password</p>

<form action="../public/create-account.php" method="post">
   <label for="Username">First and last name:</label><br>
   <input name="Username"
         placeholder="Johan" required><br><br>

  <label for="Password">Password</label><br>
  <input name="Password" type="password"
          placeholder="•••••••••••••••" required><br>


  <input type="submit" value="Submit">
</form>



<?php require_once "footer.phtml"?>
