</div>
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>D0018E Laboration</strong> by Lab Group 14.
    </p><br>
    <nav class="level">
      <div class="level-item">
        <p><a href="mailto:amouli-0@student.ltu.se">Malkolm Lundkvist</a> </p>
      </div>
      <div class="level-item">
        <p><a href="mailto:gusste-9@student.ltu.se">Gustav Österdahl Norström</a> </p>
      </div>
      <div class="level-item">
        <p><a href="mailto:frefal-9@student.ltu.se">Fredrik Falk</a> </p>
      </div>
    </nav>
  </div>
</footer>

<script src="/js/vendor/modernizr-3.11.2.min.js"></script>
<script src="/js/plugins.js"></script>
<script src="/js/main.js"></script>
<script src="/js/bulma.js"></script>
