<?php require 'header.phtml' ?>
<section class="section">

    <h1 class="title">
      <?php echo $header_attr["title"]?>
    </h1>

    <p>Hello world!</p>

     <table class="table is-striped">
       <tr>
         <th>id</th>
         <th>title</th>
         <th>price</th>
       </tr>
       <?php if (isset($product_table_html)) {
         echo $product_table_html;
       } ?>

   </table>

<?php require 'footer.phtml' ?>
