<?php require_once "header.phtml"?>
<section class="section">

<div class="card">
  <header class="card-header">
    <h1 class="card-header-title">Login</h1>

  </header>
  <div class="card-content">
    <form action="../public/login-page.php" method="post">

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Username</label>
        </div>
        <div class="field-body">
          <div class="field">
            <p class="control">
              <input class="input" name="Username" placeholder="Johan" required>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Password</label>
        </div>
        <div class="field-body">
          <div class="field">
            <p class="control">
              <input class="input" name="Password" type="password" placeholder="••••••••••" required>
            </p>
          </div>
        </div>
      </div>

    </div>
    <footer class="card-footer">
      <input type="submit" value="Submit" class="card-footer-item">
    </footer>

  </form>
</div>

<?php require_once "footer.phtml"?>
