<?php require_once "header.phtml";

?>
<section class="section">
  <div>
    <h1 class="title">Admin</h1>

    <table class="table is-striped">
      <tr>
        <th>Order id</th>
        <th>Product id</th>
        <th>Quantity</th>
        <th>Price</th>
        <th></th>
      </tr>

      <?php if (isset($order_table_html)) {
        echo $order_table_html;
      } ?>

    </table>
  </div>

  <?php require_once "footer.phtml"?>
