<?php require_once "header.phtml";
assert(isset($row));
assert(isset($id));
assert(isset($comments));
?>

<section class="hero">
  <div class="hero-body">
    <h1 class="title">
      <?php echo $row[0]?>
    </h1>
    <h2 class="subtitle">
      Author: <?php echo $row[1]?>
    </h2>
  </div>

</section>

<section class="section">
  <p>
    <?php echo $row[4]?>
  </p>
</section>
<section class="section is-small">
  <h2 class="subtitle">Comments</h2>
  <?php
  foreach ($comments as $comment) {
    require "comments.phtml";
  }?>
  <article class="media">
    <figure class="media-left">
      <p class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/128x128.png">
      </p>
    </figure>
    <div class="media-content">
      <form method="post">
        <div class="field">
          <p class="control">
            <textarea class="textarea" name="comment" placeholder="Add a comment..."></textarea>
          </p>
        </div>
        <nav class="level">
          <div class="level-left">
            <div class="level-item">
              <input type="submit" class="button is-info" value="Submit">
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <div class="control">
                Rating:
                <label class="radio">
                  <input type="radio" name="rating" value="1">
                  1
                </label>
                <label class="radio">
                  <input type="radio" name="rating" value="2">
                  2
                </label>
                <label class="radio">
                  <input type="radio" name="rating" value="3" checked>
                  3
                </label>
                <label class="radio">
                  <input type="radio" name="rating" value="4">
                  4
                </label>
                <label class="radio">
                  <input type="radio" name="rating" value="5">
                  5
                </label>
              </div>
            </div>
          </div>
        </nav>
      </form>
    </div>
  </article>
</section>





<?php require_once "footer.phtml"?>
